#include <stdint.h>
// Auto-generated stubs for Apple frameworks (Foundation/CoreML)
// The ORT static lib references these, but laya-serve never calls the CoreML EP.
void _CFRelease(void){}
void _CFStringGetCString(void){}
void _CFStringGetLength(void){}
void _CFStringGetMaximumSizeForEncoding(void){}
void _CFTimeZoneCopyDefault(void){}
void _CFTimeZoneGetName(void){}
void _NSLog(void){}
void _NSTemporaryDirectory(void){}
void* _OBJC_CLASS_$_MLComputePlan[4]={0};
void* _OBJC_METACLASS_$_MLComputePlan[4]={0};
void* _OBJC_CLASS_$_MLDictionaryFeatureProvider[4]={0};
void* _OBJC_METACLASS_$_MLDictionaryFeatureProvider[4]={0};
void* _OBJC_CLASS_$_MLFeatureValue[4]={0};
void* _OBJC_METACLASS_$_MLFeatureValue[4]={0};
void* _OBJC_CLASS_$_MLModel[4]={0};
void* _OBJC_METACLASS_$_MLModel[4]={0};
void* _OBJC_CLASS_$_MLModelConfiguration[4]={0};
void* _OBJC_METACLASS_$_MLModelConfiguration[4]={0};
void* _OBJC_CLASS_$_MLMultiArray[4]={0};
void* _OBJC_METACLASS_$_MLMultiArray[4]={0};
void* _OBJC_CLASS_$_MLOptimizationHints[4]={0};
void* _OBJC_METACLASS_$_MLOptimizationHints[4]={0};
void* _OBJC_CLASS_$_MLPredictionOptions[4]={0};
void* _OBJC_METACLASS_$_MLPredictionOptions[4]={0};
void* _OBJC_CLASS_$_NSFileManager[4]={0};
void* _OBJC_METACLASS_$_NSFileManager[4]={0};
void* _OBJC_CLASS_$_NSMutableArray[4]={0};
void* _OBJC_METACLASS_$_NSMutableArray[4]={0};
void* _OBJC_CLASS_$_NSMutableDictionary[4]={0};
void* _OBJC_METACLASS_$_NSMutableDictionary[4]={0};
void* _OBJC_CLASS_$_NSMutableString[4]={0};
void* _OBJC_METACLASS_$_NSMutableString[4]={0};
void* _OBJC_CLASS_$_NSNumber[4]={0};
void* _OBJC_METACLASS_$_NSNumber[4]={0};
void* _OBJC_CLASS_$_NSProcessInfo[4]={0};
void* _OBJC_METACLASS_$_NSProcessInfo[4]={0};
void* _OBJC_CLASS_$_NSString[4]={0};
void* _OBJC_METACLASS_$_NSString[4]={0};
void* _OBJC_CLASS_$_NSURL[4]={0};
void* _OBJC_METACLASS_$_NSURL[4]={0};
